num_classes: 10
epochs: 100
grad_clip: 5.0
log_frequency: 10
model:
  name: ResNet
  block: Bottleneck
  num_blocks:
    - 3
    - 4
    - 6
    - 3
  activation: Mish
  resolution:
    - 32
    - 32
  mhsa4: True
  heads4: 8
  cbam: True
criterion:
  name: TradesLoss
  epsilon: 0.03137254901960784
  perturb_steps: 10
  step_size: 0.00784313725490196
dataset:
  name: DatasetGenerator
  train_batch_size: 256
  eval_batch_size: 256
  num_of_workers: 8
  dataset_type: CIFAR10
  data_path: /data/huangshihua/CIFAR10
optimizer:
  name: Adam
  lr: 0.001
#  weight_decay: 0.0002
#  name: SGD
#  lr: 0.01
#  weight_decay: 0.0002
#  momentum: 0.9
scheduler:
  name: MultiStepLR
  milestones:
  - 75
  - 90
  - 100
  gamma: 0.1



