#num_classes: 10
#epochs: 100
#grad_clip: 5.0
#log_frequency: 10
#model:
#  name: ResNet
#  block: Bottleneck
#  num_blocks:
#    - 3
#    - 4
#    - 6
#    - 3
#criterion:
#  name: TradesLoss
#  epsilon: 0.03137254901960784
#  perturb_steps: 10
#  step_size: 0.00784313725490196
#dataset:
#  name: DatasetGenerator
#  train_batch_size: 512
#  eval_batch_size: 512
#  num_of_workers: 8
#  dataset_type: CIFAR10
#  data_path: /data/huangshihua/CIFAR10
#optimizer:
#  name: SGD
#  lr: 0.1
#  weight_decay: 0.0002
#  momentum: 0.9
#scheduler:
#  name: MultiStepLR
#  milestones:
#  - 75
#  - 90
#  - 100
#  gamma: 0.1

num_classes: 10
epochs: 20
grad_clip: 5.0
log_frequency: 10
model:
  name: PreActResNet
  channel_configs:  # [20, 20, 8]
  - 16
  - 80
  - 224
  - 192
  depth_configs:
  - 14
  - 14
  - 7
  drop_rate_config:
  - 0.0
  - 0.0
  - 0.0
  num_classes: 10
  stride_config:
  - 1
  - 2
  - 2
  zero_init_residual: false
  block_types:
  - basic_block
  - basic_block
  - basic_block
  activations:
  - ReLU
  - ReLU
  - ReLU
  kernel_size_configs:
  - 3
  - 3
  - 3
  normalizations:
  - BatchNorm
  - BatchNorm
  - BatchNorm
criterion:
  name: CrossEntropyLoss
#  epsilon: 0.03137254901960784 # 8 / 255
#  perturb_steps: 10
#  step_size: 0.00784313725490196
dataset:
  name: DatasetGenerator
  train_batch_size: 1024
  eval_batch_size: 512
  num_of_workers: 8
  dataset_type: CIFAR10
  data_path: /data/huangshihua/CIFAR10
optimizer:
  name: SGD
  lr: 0.1
  weight_decay: 0.0002
  momentum: 0.9
scheduler:
  name: MultiStepLR
  milestones:
  - 75
  - 90
  - 100
  gamma: 0.1

