num_classes: 10
epochs: 200
grad_clip: 5.0
log_frequency: 10
model:
  name: Wide_ResNet
  depth: 28
  widen_factor: 10
  dropout_rate: 0.3
  num_classes: 10
criterion:
  name: TradesLoss
  epsilon: 0.03137254901960784
  perturb_steps: 10
  step_size: 0.00784313725490196
dataset:
  name: DatasetGenerator
  train_batch_size: 1024
  eval_batch_size: 512
  num_of_workers: 8
  dataset_type: CIFAR10
  data_path: /data/huangshihua/CIFAR10
optimizer:
#  name: Adam
#  lr: 0.01
#  weight_decay: 0.0002
  name: SGD
  lr: 0.01
  weight_decay: 0.0002
  momentum: 0.9
scheduler:
  name: MultiStepLR
  milestones:
  - 75
  - 90
  - 100
  gamma: 0.1



